export const USERS_TABLE = [
  {
    id: 1,
    name: "Emre",
    surname: "Erdem",
    nick: "emrerdem1",
    email: "",
    age: 25,
    registeredAt: "",
    avatar: "https://source.unsplash.com/random/60x60",
  },
  {
    id: 2,
    name: "John",
    surname: "Doe",
    nick: "john_doe",
    email: "",
    age: 32,
    registeredAt: "",
    avatar: "https://source.unsplash.com/random/60x61",
  },
  {
    id: 3,
    name: "Mary",
    surname: "Jane",
    nick: "mary_jane",
    email: "",
    age: 24,
    registeredAt: "",
    avatar: "https://source.unsplash.com/random/60x62",
  },
  {
    id: 4,
    name: "Peter",
    surname: "Pan",
    nick: "peter_pan",
    email: "",
    age: 62,
    registeredAt: "",
    avatar: "https://source.unsplash.com/random/60x63",
  },
];
